name: update-news
on:
  schedule: [{ cron: '*/5 * * * *' }]
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NEWS_FEED_URL: https://www.pref.tottori.lg.jp/services/rdf/rss10/589717.xml
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl \
            -sL "https://api.rss2json.com/v1/api.json?rss_url=${NEWS_FEED_URL}" \
          | jq '{
            newsItems: [
              .items[:3][]
              | {
                date: "\(.pubDate | sub(" ";"T"))Z",
                url:  .link,
                text: .title
              }
            ]
          }' \
          | ruby \
            -rcgi \
            -pe '$_=CGI.unescape_html($_)' \
          | tee data/news.json
      - run: git add data/news.json
      - run: git -c "user.name=${GITHUB_ACTOR}" -c "user.email=${GITHUB_ACTOR}@users.noreply.github.com" commit -m update-news
        continue-on-error: true
      - run: git push origin HEAD
